version: '3.7'

services:

    app:
        container_name: nature-whisper
        build:
            context: .
            dockerfile: Dockerfile
        volumes: 
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3001:3000
        environment: 
            - CHOKADIR_USEPOLLING=true
        stdin_open: true